import {useRef,useState} from 'react';import {Header} from './Episodes';import {useGame} from '../store/gameStore';
const backupKeys=['name','coins','episode','unlockedEpisode','completed','affinity','traits','route','flags','choices','unlockedCG','ownedOutfits','equipped','visited','eventDone','messages','history','decisionLog','settings'] as const;
export function Settings(){
 const g=useGame();const input=useRef<HTMLInputElement>(null);const [status,setStatus]=useState('');
 const exportSave=()=>{const s=useGame.getState() as any;const state=Object.fromEntries(backupKeys.map(k=>[k,s[k]]));const payload={format:'aurora-save',version:4,exportedAt:new Date().toISOString(),state};const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.href=url;a.download='aurora-v4-save.json';a.click();URL.revokeObjectURL(url);setStatus('Backup exportado.')};
 const importSave=async(file?:File)=>{if(!file)return;try{const parsed=JSON.parse(await file.text());if(parsed?.format!=='aurora-save'||!parsed.state||typeof parsed.state.name!=='string'||!parsed.state.affinity)throw new Error('invalid');const patch=Object.fromEntries(backupKeys.filter(k=>k in parsed.state).map(k=>[k,parsed.state[k]]));useGame.setState({...patch,playerOpen:false,autoMode:false} as any);setStatus('Backup restaurado com sucesso.')}catch{setStatus('Esse arquivo não parece um save válido do Aurora.')}finally{if(input.current)input.current.value=''}};
 return <><Header title="Ajustes" text="Leitura, acessibilidade e segurança do seu progresso."/><div className="settings">
  <article><h3>Velocidade do texto</h3><p>Controle o efeito de digitação durante os diálogos.</p><select value={g.settings.textSpeed} onChange={e=>g.setSettings({textSpeed:+e.target.value})}><option value={0}>Instantâneo</option><option value={6}>Muito rápido</option><option value={12}>Normal</option><option value={24}>Lento</option><option value={40}>Muito lento</option></select></article>
  <article><h3>Modo automático</h3><p>Tempo de espera depois que uma fala termina.</p><input type="range" min="700" max="4000" step="100" value={g.settings.autoDelay} onChange={e=>g.setSettings({autoDelay:+e.target.value})}/><b>{(g.settings.autoDelay/1000).toFixed(1)}s</b></article>
  <article><h3>Movimento reduzido</h3><p>Desativa animações desnecessárias no player.</p><label className="settingToggle"><input type="checkbox" checked={g.settings.reducedMotion} onChange={e=>g.setSettings({reducedMotion:e.target.checked})}/><span>{g.settings.reducedMotion?'Ativado':'Desativado'}</span></label></article>
  <article><h3>Alto contraste</h3><p>Reforça caixa de diálogo e controles.</p><label className="settingToggle"><input type="checkbox" checked={g.settings.highContrast} onChange={e=>g.setSettings({highContrast:e.target.checked})}/><span>{g.settings.highContrast?'Ativado':'Desativado'}</span></label></article>
  <article><h3>Volume geral</h3><p>Preparado para trilha, voz e efeitos do mixer.</p><input type="range" min="0" max="1" step=".05" value={g.settings.masterVolume} onChange={e=>g.setSettings({masterVolume:+e.target.value})}/><b>{Math.round(g.settings.masterVolume*100)}%</b></article>
  <article><h3>Backup do save</h3><p>Exporte ou restaure seu progresso local em JSON.</p><div className="settingsActions"><button onClick={exportSave}>Exportar</button><button onClick={()=>input.current?.click()}>Importar</button><input ref={input} hidden type="file" accept=".json,application/json" onChange={e=>importSave(e.target.files?.[0])}/></div>{status&&<small>{status}</small>}</article>
  <article><h3>Reiniciar campanha</h3><p>Apaga progresso, relações, decisões e memórias locais.</p><button onClick={()=>confirm('Reiniciar toda a campanha? Essa ação não pode ser desfeita sem um backup.')&&g.resetGame()}>Reiniciar tudo</button></article>
 </div></>
}